name: Packer

on:
  push:
    paths: 
      - '*.json'
      - 'bootstrap_win.txt'
      - '.github/workflows/packer.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    container: docker://hashicorp/packer:1.4.3

    steps:
    - uses: actions/checkout@v1
    - run: packer validate windows.json
    - run: packer build windows.json
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-northeast-1
